In [19]:
# Import required libraries
import pandas as pd
import os
import csv
from datetime import datetime, timedelta

In [20]:
# From the operating system get the current working direcotry
os.getcwd()

'/Users/rodneydavermann/Desktop/Tableau-Challenge'

In [21]:
# Display the file names inside the working directory
files = os.listdir()
files

['.DS_Store',
 'README.md',
 '.ipynb_checkpoints',
 '.git',
 'Data',
 'citybike.ipynb']

In [23]:
# Read csv bike data files 
bike_data_202101 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202101-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202012 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202012-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202011 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202011-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202010 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202010-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202009 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202009-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202008 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202008-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202007 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202007-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202006 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202006-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202005 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202005-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202004 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202004-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202003 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202003-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202002 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202002-citibike-tripdata.csv", error_bad_lines=False)
bike_data_202001 = pd.read_csv("/Users/rodneydavermann/Desktop/Tableau-Challenge/Data/JC-202001-citibike-tripdata.csv", error_bad_lines=False)

In [25]:
# Create a list with all the csv files
bike_all_data = [bike_data_202101,bike_data_202012,bike_data_202011,bike_data_202010,bike_data_202009,bike_data_202008,bike_data_202007,bike_data_202006,bike_data_202005,bike_data_202004,bike_data_202003,bike_data_202002,bike_data_202001]

In [27]:
# Merge all files together with the concatenate function
bike_all_df = pd.concat(bike_all_data)

In [28]:
bike_all_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26015,544,2020-01-31 23:29:29.3910,2020-01-31 23:38:33.6910,3213,Van Vorst Park,40.718489,-74.047727,3194,McGinley Square,40.725340,-74.067622,29659,Subscriber,1989,1
26016,122,2020-01-31 23:30:59.3670,2020-01-31 23:33:01.6870,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42361,Subscriber,1991,1
26017,201,2020-01-31 23:42:34.8460,2020-01-31 23:45:55.8780,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42368,Subscriber,1988,1
26018,300,2020-01-31 23:45:00.6800,2020-01-31 23:50:00.8740,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,42257,Subscriber,1981,2
26019,721,2020-01-31 23:48:35.1700,2020-02-01 00:00:36.4060,3206,Hilltop,40.731169,-74.057574,3202,Newport PATH,40.727224,-74.033759,29302,Customer,1998,1

In [31]:
# Convert and export the final file
bike_all_df.to_csv("bike_cities.csv")

In [34]:
bike_all_df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [35]:
bike_all_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 348426 entries, 0 to 26019
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tripduration             348426 non-null  int64
 1   starttime                348426 non-null  object
 2   stoptime                 348426 non-null  object
 3   start station id         348426 non-null  int64
 4   start station name       348426 non-null  object
 5   start station latitude   348426 non-null  float64
 6   start station longitude  348426 non-null  float64
 7   end station id           348426 non-null  int64
 8   end station name         348426 non-null  object
 9   end station latitude     348426 non-null  float64
 10  end station longitude    348426 non-null  float64
 11  bikeid                   348426 non-null  int64
 12  usertype                 348426 non-null  object
 13  birth year               348426 non-null  int64
 14  gender                   348426 non-null  int64
dtypes: float64(4), int64(6), object(5)
memory usage: 42.5+ MB